# -*- coding: utf-8 -*-
"""
Created on Tue Sep 24 14:30:24 2024

@author: Dylan 
"""

#%% Import
import os
import matplotlib.pyplot as plt
from psychopy import visual, core

#%% Window

# Create a small screen window, 
screen_size = [400,400]
win = visual.Window(size=screen_size, 
                    color=(0.5,0.5,0.5),
                    fullscr=False, 
                    units='pix')


#%% Show Block 1
image_dir = '/Users/rick/OneDrive/Documents/PSY 627 Data/fLoc_stimuli/';

image_file = os.path.join(image_dir, 'adult-5.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'child-4.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'adult-1.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'child-2.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'adult-15.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'child-14.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'adult-9.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'child-10.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'adult-7.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'child-8.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'adult-12.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'child-11.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'adult-13.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'child-12.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'adult-20.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'child-15.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(3.25)

# Show Block 2

image_file = os.path.join(image_dir, 'corridor-5.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'house-4.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'corridor-1.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'house-2.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'corridor-15.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'house-14.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'corridor-9.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'house-10.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'corridor-7.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'house-8.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'corridor-12.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'house-11.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'corridor-13.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'house-12.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'corridor-20.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'house-15.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(3.25)

# Show Block 3

image_file = os.path.join(image_dir, 'car-5.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'instrument-4.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'car-1.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'instrument-2.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'car-15.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'instrument-14.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'car-9.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'instrument-10.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'car-7.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'instrument-8.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'car-12.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'instrument-11.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'car-13.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'instrument-12.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'car-20.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'instrument-15.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(-screen_size[0]//2 + 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(3.25)

# Show Block 4

image_file = os.path.join(image_dir, 'adult-5.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'child-4.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'adult-1.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'child-2.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'adult-15.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'child-14.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'adult-9.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'child-10.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'adult-7.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'child-8.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'adult-12.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'child-11.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'adult-13.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'child-12.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'adult-20.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'child-15.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(3.25)

# Show Block 5

image_file = os.path.join(image_dir, 'corridor-5.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'house-4.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'corridor-1.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'house-2.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'corridor-15.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'house-14.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'corridor-9.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'house-10.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'corridor-7.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'house-8.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'corridor-12.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'house-11.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'corridor-13.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'house-12.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'corridor-20.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'house-15.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(3.25)

# Show Block 6

image_file = os.path.join(image_dir, 'car-5.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'instrument-4.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'car-1.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'instrument-2.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'car-15.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'instrument-14.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'car-9.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'instrument-10.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'car-7.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'instrument-8.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'car-12.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'instrument-11.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'car-13.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'instrument-12.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file = os.path.join(image_dir, 'car-20.jpg')
img = visual.ImageStim(win, image=image_file, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(.25)
image_file2 = os.path.join(image_dir, 'instrument-15.jpg')
img = visual.ImageStim(win, image=image_file2, units='pix', size=(200,200), pos=(screen_size[0]//2 - 150, 0))
img.draw()
win.flip()
core.wait(1.0)
win.flip()
core.wait(3.25)

#Next time I am making a variable for screen size to save time

#%% Close window
win.close()

